### ISSUE TITLE
Allow Bottleneck limiter options to be overridden

### ISSUE THREAD

**Issue by AustinLeeGordon** [HGData/mk-node-hubspot#153]
Would like to be able to override the Bottleneck limiter options (or at least fix the default options) to allow for requests to be processed concurrently.

In the [current version](https://github.com/MadKudu/node-hubspot/tree/169e0f56795411d5cdf425265e4c074154f559d3) the Bottleneck limiter has `minTime` set to 1000, delaying each request by 1s. I think it was intended to allow for 9 concurrent requests with `maxConcurrent` set to 9, but it will almost always only run one at a time since requests should resolve before the 1s delay.

https://github.com/MadKudu/node-hubspot/blob/169e0f56795411d5cdf425265e4c074154f559d3/lib/client.js#L20-L24

Changing `minTime` to something like 1000 / 9 will keep it under the 10 requests per second limit. 

```js
const Bottleneck = require('bottleneck')
const limiter = new Bottleneck({
  maxConcurrent: 9,
  minTime: 1000 / 9,
})
```

Might need some tweaking to account for errors. In one application where I tested it, some of the emails being uploaded would bounce back errors and cause some of  the following requests to hit the limit.

I'd be happy to work on a PR for this, but I wanted to make sure there weren't any other gotchas that I needed to watch out for.

**Comment by SGrondin** [comment]
Hey @AustinLeeGordon , author of Bottleneck here. First of all, thank you for using it.

>In the current version the Bottleneck limiter has minTime set to 1000, delaying each request by 1s. I think it was intended to allow for 9 concurrent requests with maxConcurrent set to 9, but it will almost always only run one at a time since requests should resolve before the 1s delay.

Your understanding of the way it works is correct. I think the original author misunderstood how minTime and maxConcurrent work. I improved the docs a while ago, but it was frequent for people to think `minTime: 1000, maxConcurrent: 9` meant `9 requests per second`. You see why this is obviously wrong. It's something I used to see a lot when browsing uses of Bottleneck on Github.

Here are my recommendations:
- I'd change `minTime` to `1000 / 9`, like you said.
- I'd set `maxConcurrent` to a lower value, maybe `2` or `3`. I think the rate limit errors you're seeing are because you end up having too many requests in progress at the same time.

`1000/9` is 1 request started every 111ms. If your average request takes 500ms, it means that you'll have up to 5 requests in progress at any time, on average. That's usually too much for most APIs out there. Of course I think you should have a look at the hubspot recommended best practices and make sure these numbers are acceptable.

Good luck, and please lemme know if I can help!

**Comment by pcothenet** [comment]
I'm all for it. You already did the `/9` in #152 , right?

**Comment by AustinLeeGordon** [comment]
@pcothenet I made it `1000 / 8`. Had a few that errored and caused it to hit the 10/second limit when I was testing it out. Not sure what the best mix would be between the `minTime` and `maxConcurrent` values, but I can play with it and see what seems to work best. Might lower `maxConcurrent` as @SGrondin suggested and see what happens. Also would need to set it up to accept a different value, but that shouldn’t be too bad.

**Comment by pcothenet** [comment]
Got it. Want to leave this open in the meantime?

**Comment by AustinLeeGordon** [comment]
@pcothenet Sounds good, thanks!
